name: NASA CI
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build:
        env:
            CI: true
        strategy:
            matrix:
                node-version: [16.x, 17.x, 18.x]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js version ${{matrix.node-version}}
              uses: actions/setup-node@v2
              with: node-version:${{matrix.node-version}}
            - run: npm install
            - run: npm run build --prefix client
            - run: npm test
